# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03e0da8ee8c45d36f5c6a8acc3d5a781d3ddab99c4e003a4159c176066f81a6a71649ba08f6dd3151740d32bed969950aa96bc9dd2a81df858b012032f782dcb

test:
  secret_key_base: 833d0bdbfa2f4348a068ea2062c4debe4f6cdbad46f78c0c372f55c124069c71b744c93d20ff1b7eef3343019b6f45f356805b07ba97bf099f23cb27c06b2d4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
